---
title: "countries_interest_rates"
author: "Nandhini Sridhar"
output: html_document
date: "2023-11-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(tidyverse)
library(readxl)
library(ggplot2)
library(fuzzyjoin) #fuzzy matching of strings
library(lfe) #fixed effects regression
library(fixest) #fixed effects regression

#packages
#lfe - install.packages("lfe")
#fixest - install.packages("fixest")
```

DATA CLEANING
```{r}
setwd("/Users/NandhiniSridhar/Desktop/econ_honors_thesis")
mfdata <- read_excel("/Users/NandhiniSridhar/Desktop/econ_honors_thesis/data/Microfinance/mix-market-financial-performance-dataset-in-usd.xlsx")
#View(mfdata)

country_data <- read_excel("/Users/NandhiniSridhar/Desktop/econ_honors_thesis/data/Microfinance/COUNTRY_CODEBOOKmix-market-mfi-company-metadata.xlsx")
#View(country_data)

names(mfdata) <- gsub(' ', '_', names(mfdata))
names(country_data) <- gsub(' ', '_', names(country_data))

ir <- read_excel("/Users/NandhiniSridhar/Desktop/econ_honors_thesis/data/Microfinance/Interest_Rates.xlsx")
colnames(ir)
cols <- c("Country", "Scale", "Base Year")
for (i in 2000:2021){
  cols <- cols %>% append(i)
}
print(cols)
names(ir) <- cols
ir <- ir[6:nrow(ir),]
```

```{r}
mfdata['Country'] <- NA
countries <- c()
enter <- c()
ifc <- c()
elsec <- c()
names <- c()

#get the countries of each bank in the mfi dataset
for (i in 1:nrow(mfdata)) {
  mfi_name <- mfdata$MFI_Name[i]
  enter <- enter %>% append(1)
  
  if(mfi_name %in% country_data$MFI_Name){
    ifc <- ifc %>% append(1)
    country_name <- country_data$Country[country_data$MFI_Name == mfi_name]
    names <- names %>% append(length(country_name))
    countries <- countries %>% append(country_name)
    #mfdata[i, 'country'] <- country_name
  }
  else{
    elsec <- elsec %>% append(1)
    countries <- countries %>% append("NOT FOUND")
  }
}

# get rid of ones with multiple countries (would have repeats of the same country for some reason)
names2 <- c()
for(i in 1:length(names)){
  if(names[i] == 2){
    names2 <- names2 %>% append(1)
    cat(names[i], ": ", countries[i], "\n")
    countries <- countries[-i]
  }
}

#append to mfi dataset
mfdata$Country <- countries
```

```{r}
#arrange by MFI name and fiscal year
mfdata <- mfdata %>% filter(Period_Type == "ANN") %>% arrange(MFI_Name, Fiscal_Year)
#mfdata['country_reduced'] <- gsub(",.*", "", mfdata$country)
#mfdata['country_reduced'] <- gsub("\\(.*", "", mfdata$country)
#names(country_data) <- gsub(' ', '_', names(country_data))

mf_interest <- stringdist_join(mfdata, ir, 
                by='Country', 
                mode='left',
                method = "soundex") %>%
  arrange(Country.x)


#Ratio_GLP_Female is the y variable - the percentage of loan money that goes to women borrowers
mf_interest %>% drop_na(`Gross_Loan_Portfolio`)
mf_interest %>% drop_na(`Gross_Loan_Portfolio_>_Gender_>_Female`)

mf_interest$Ratio_GLP_Female = mf_interest$`Gross_Loan_Portfolio_>_Gender_>_Female` / mf_interest$Gross_Loan_Portfolio

```

```{r}
#encode by region
#World Bank region classifications: Africa, East Asia & the Pacific, Europe & Central Asia, Latin America & The Caribbean, Middle East & North Africa, South Asia
africa <- c("Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cameroon", "Cabo Verde", "Central African Republic", "Chad", "Comoros", "Cote d'Ivore", "Cote d'Ivoire (Ivory Coast)", "Congo", "Congo, Democratic Republic of the","Congo, Republic of the", "Equitorial Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Ghana", "Gambia", "Gambia, The", "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Madagascar", "Malawi", "Mali", "Mauritus", "Mozambique", "Nambia", "Niger", "Nigeria", "Rwanda", "Senegal", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Tanzania", "Togo", "Uganda", "Zambia", "Zimbabwe", "Namibia", "Swaziland")

east_asia_pacific <- c("Cambodia", "China", "China, People's Republic of", "Indonesia", "Korea", "Lao PDR", "Malaysia", "Mongolia", "Myanmar", "Papua New Guinea", "Philippines", "Singapore", "Thailand", "Vietnam", "East Timor", "Laos", "Myanmar (Burma)", "Samoa", "Solomon Islands", "Tonga", "Vanuatu")

europe_central_asia <- c("Albania", "Armenia", "Azerbaijan", "Belarus", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Georgia", "Hungary", "Kazakhstan", "Kosovo", "Kyrgyzstan", "Moldova", "Montenegro", "Macedonia", "Poland", "Romania", "Russia", "Serbia", "Tajikistan", "Turkey", "Turkmenistan", "Ukraine", "Uzbekistan", "Slovakia")

latin_america_caribbean <- c("Argentina", "Belize", "Bolivia", "Brazil", "Colombia", "Chile", "Costa Rica", "Dominican Republic", "Ecuador", "El Salvador", "Grenada", "Guatemala", "Guyana", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Paraguay", "Peru", "Saint Lucia", "Suriname", "Trinidad and Tobago", "Uruguay", "Venezuela", "Fiji")

middle_east_north_africa <- c("Algeria", "Bahrain", "Djibouti", "Egypt", "Iran", "Iraq", "Jordan", "Kuwait", "Lebanon", "Libya", "Morocco", "Oman", "Palestine", "Qatar", "Saudi Arabia", "Syria", "Tunisia", "United Arab Emirates", "Yemen", "Israel")

south_asia <- c("Sri Lanka", "Bangladesh", "India", "Afghanistan", "Pakistan", "Bhutan", "Nepal", "Maldives")

north_america <- c("United States", "Canada")

mf_interest <- mf_interest %>% 
  mutate(Region = case_when(
    Country.x %in% africa ~ 'Sub_Saharan_Africa',
    Country.x %in% east_asia_pacific ~ 'East_Asia_Pacific',
    Country.x %in% europe_central_asia ~ 'Europe_Central_Asia',
    Country.x %in% middle_east_north_africa ~ 'Middle_East_North_Africa',
    Country.x %in% north_america ~ 'North_America',
    Country.x %in% latin_america_caribbean ~ 'Latin_America_Caribbean',
    Country.x %in% south_asia ~ 'South_Asia',
    TRUE ~ 'Other'))

x <- mf_interest %>% filter(Region == "Other") %>% select(Country.x)
print(unique(x))
```

```{r}
# instrumental variable is the interest rate for a given year
# here i create the variable that can be used as a common instrument (interest rates are originally split one year per column)
# here i only take the interest rate that directly corresponds to the fiscal year for a given entry

mf_interest$Cur_Interest_Rate = 9999 #this is the error code


for(i in 1:nrow(mf_interest)){
  year = mf_interest$Fiscal_Year[i]
  if(mf_interest$Fiscal_Year[i] != 1999){
    if(mf_interest[i, as.character(year)] != "..." & !is.na(mf_interest[i, as.character(year)]) & mf_interest[i, as.character(year)] != "-"){
      #print(i)
      #print(mf_interest[i, as.character(year)])
      mf_interest$Cur_Interest_Rate[i] <- mf_interest[i, as.character(year)]
    }
  }
  #if(suppressWarnings(is.na(as.numeric(mf_interest$Cur_Interest_Rate))[i])){
  #  print(mf_interest$Cur_Interest_Rate[i])
  #}
}
#unique(mf_interest$Cur_Interest_Rate)

mf_interest$Cur_Interest_Rate <- as.numeric(mf_interest$Cur_Interest_Rate)
```

```{r}
mf_interest <- mf_interest %>% drop_na("Gross_Loan_Portfolio")
mf_interest <- mf_interest %>% drop_na("Ratio_GLP_Female")
mf_interest <- mf_interest %>% drop_na("Percent_of_female_borrowers")


working_mf_interest <- mf_interest %>% filter(Cur_Interest_Rate != 9999)
working_mf_interest <- working_mf_interest %>% drop_na("Cur_Interest_Rate")
```

```{r}
#run everything above this to clean and preprocess data
```

BACKGROUND INFO + TABLES / DATA EXPLORATION
```{r}
#mfdata - all MIX Market data
print(length(unique(mfdata$MFI_Name)))
print(length(unique(mfdata$Country.x)))

ggplot(mfdata, aes(x=Country)) + 
  geom_bar() +
  theme(axis.text.x = element_text(size=5, angle = 90, vjust = 1, hjust=1))
```

```{r}
#working data - mfis with interest data fir relevant years
print(length(unique(working_mf_interest$MFI_Name)))
print(length(unique(working_mf_interest$Country.x)))

ggplot(working_mf_interest, aes(x=Country.x)) + 
  geom_bar() +
  theme(axis.text.x = element_text(size=5, angle = 90, vjust = 1, hjust=1))

#use for GLP, %women borrowers, %GLP to women over time for all data
min <- min(working_mf_interest$Fiscal_Year)
max <- max(working_mf_interest$Fiscal_Year)
total <- ranges <- data.frame(matrix(ncol=(max - min + 1), nrow=0))
colnames(total) <- c('Fiscal Year', 'Total_GLP')


ggplot(working_mf_interest, aes(x=Fiscal_Year, y=Gross_Loan_Portfolio)) +
  geom_line() +
  scale_x_continuous(breaks = seq(min(working_mf_interest$Fiscal_Year), max(working_mf_interest$Fiscal_Year), by=1)) +
  labs(title = "Gross Loan Portfolios Over Time Across all MFIs")
  
```


REGRESSIONS FROM HERE AND BELOW
```{r}
#basic model, no fixed effects
basic_linear <- lm(Ratio_GLP_Female ~ Gross_Loan_Portfolio, data=mf_interest)
summary(basic_linear)

basic_log <- lm(Ratio_GLP_Female ~ log(Gross_Loan_Portfolio), data=mf_interest)
summary(basic_log)


#With time and mfi fixed effects
#the 0 means no instrumental variables
#what standard error clustering dim do i use (right now doing it by mfi)
time_mfi_fe <- felm(Ratio_GLP_Female ~ log(Gross_Loan_Portfolio) | MFI_Name + Fiscal_Year | 0 | MFI_Name, mf_interest)
summary(time_mfi_fe)

#negative coef

#include region fixed effects
time_region_fe <- felm(Ratio_GLP_Female ~ log(Gross_Loan_Portfolio) | Region + Fiscal_Year | 0 | MFI_Name, mf_interest)
summary(time_region_fe)

```


```{r}
#instrumental variable only, no fixed effects, still using log of GLP

#looking at raw change in GLP based on change in interest rate (which is already in percentage points)
#dont use
ir_inst_step1 <- lm(Gross_Loan_Portfolio ~ Cur_Interest_Rate, data=working_mf_interest)
summary(ir_inst_step1)
working_mf_interest$predicted_GLP <- predict(ir_inst_step1)

ir_inst_step2 <- lm(Ratio_GLP_Female ~ log(predicted_GLP), data = working_mf_interest)
summary(ir_inst_step2)


#looking at percent change in GLP based on change in interest rate (which is already in percentage points)
ir_log_inst_step1 <- lm(log(Gross_Loan_Portfolio) ~ Cur_Interest_Rate, data=working_mf_interest)
summary(ir_log_inst_step1)
working_mf_interest$predicted_GLP <- predict(ir_log_inst_step1)

ir_log_inst_step2 <- lm(Ratio_GLP_Female ~ log(predicted_GLP), data = working_mf_interest)
summary(ir_log_inst_step2)
```
```{r}
summary(mf_interest$Percent_of_female_borrowers)
sd(mf_interest$Percent_of_female_borrowers)
summary(mf_interest$Gross_Loan_Portfolio)
sd(mf_interest$Gross_Loan_Portfolio)
sd(log(mf_interest$Gross_Loan_Portfolio))

```

```{r}
#percent is from 0 to 1

time_mfi_fe <- felm(Percent_of_female_borrowers ~ log(Gross_Loan_Portfolio) | MFI_Name + Fiscal_Year | 0 | MFI_Name, mf_interest)
summary(time_mfi_fe)

time_region_fe <- felm(Percent_of_female_borrowers ~ log(Gross_Loan_Portfolio) | Country.x + Fiscal_Year | 0 | MFI_Name, mf_interest)
summary(time_region_fe)

#include region fixed effects
time_region_fe <- felm(Percent_of_female_borrowers ~ log(Gross_Loan_Portfolio) | Region + Fiscal_Year | 0 | MFI_Name, mf_interest)
summary(time_region_fe)

```



This is the main regression I use
Includes both time and MFI fixed effects and interest rate as an instrumental variable

```{r}
working_mf_interest <- working_mf_interest %>% filter(Region == "South_Asia" | Region == "Latin_America_Caribbean" | Region == "Sub_Saharan_Africa")

fe_inst_1 <- feols(log(Gross_Loan_Portfolio) ~ Cur_Interest_Rate | MFI_Name + Fiscal_Year, cluster="MFI_Name", data=working_mf_interest, )
summary(fe_inst_1)

working_mf_interest$predicted_log_GLP <- predict(fe_inst_1, new_data=working_mf_interest$predicted_log_GLP)

fe_inst_2 <- feols(Ratio_GLP_Female ~ predicted_log_GLP | MFI_Name + Fiscal_Year, cluster="MFI_Name", data=working_mf_interest)
summary(fe_inst_2)
```

```{r}
#first stage here is weak so second stage isn't working, fixed effects are doing everything
working_mf_interest <- working_mf_interest %>% filter(Region == "South_Asia" | Region == "Latin_America_Caribbean" | Region == "Sub_Saharan_Africa")

fe_inst_1 <- feols(log(Gross_Loan_Portfolio) ~ Cur_Interest_Rate | Region + Fiscal_Year, cluster="MFI_Name", data=working_mf_interest, )
summary(fe_inst_1)

working_mf_interest$predicted_log_GLP <- predict(fe_inst_1, new_data=working_mf_interest$predicted_log_GLP)

fe_inst_2 <- feols(Percent_of_female_borrowers ~ predicted_log_GLP | Region + Fiscal_Year, cluster="MFI_Name", data=working_mf_interest)
summary(fe_inst_2)
```

```{r}
working_mf_interest <- working_mf_interest %>% filter(Region == "South_Asia" | Region == "Latin_America_Caribbean" | Region == "Sub_Saharan_Africa")

fe_inst_1 <- feols(log(Gross_Loan_Portfolio) ~ Cur_Interest_Rate | Country.x + Fiscal_Year, cluster="MFI_Name", data=working_mf_interest, )
summary(fe_inst_1)

working_mf_interest$predicted_log_GLP <- predict(fe_inst_1, new_data=working_mf_interest$predicted_log_GLP)

fe_inst_2 <- feols(Ratio_GLP_Female ~ predicted_log_GLP | Country.x + Fiscal_Year, cluster="MFI_Name", data=working_mf_interest)
summary(fe_inst_2)
```

```{r}
#to run above
```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
